#### 3.0.1_fvs_to_raster_wf_emissions_90p.R
#### Associates wildfire FVS emissions with pixel locations via TreeMap imputation.
#### For each FVS variant: reclassifies the TMFM2020 raster using per-stand emissions
#### for each flame length bin, then computes the mean emissions arising from the
#### highest 10% of flame length probabilities (excluding lowest 90%).
#### Parallelizes over variants (not FL bins) for full worker utilization.
#### Outputs: per-variant rasters in data/dp_FVS_postprocess/{wf_run_name}_90p/{VARIANT}/
#### Variant rasters are mosaicked into CONUS layers in 3.2_variant_rasters_merge.R


## ---- Configuration ----

library(here)
source(here("code/FVS_dp/cleaned_workflow/0.0_setup.R"))

# Completed wildfire wet run to rasterize
wf_run_name <- "Wildfire_WetRun_21May26_0855"

# Pre-clipped TreeMap rasters directory (generated by 0.2_tm_clip.R)
tm_clip_dir <- here("data/tm_clip_rasters")

# Pre-clipped FL rasters directory (generated by 0.3_fl_clip.R)
fl_clip_dir <- here("data/fl_clip_rasters")


## ---- Setup ----

all_dbs <- list.files(here("FVS_runs/full", wf_run_name, "outputs"), full.names = TRUE)

outpath_root <- here("data/dp_FVS_postprocess", paste0(wf_run_name, "_90p"))
dir.create(outpath_root, showWarnings = FALSE)

# Unique variants present in run outputs
run_variants <- str_sub(basename(all_dbs), -5, -4) %>% unique()

# Assume all variants have the same FL levels (from wildfire config)
# If variants have different FL levels, this will need to be computed per-variant
fl_levels <- c(1, 3, 5, 7, 10, 20)
fl_colnames <- paste0("FL", fl_levels)


## ---- Per-variant processing function (to be parallelized) ----

process_variant_all_fls_90p <- function(variant, all_dbs_input, tm_clip_dir_input, 
                                        fl_clip_dir_input, fl_colnames_input, 
                                        outpath_root_input) {
  
  message("Processing variant: ", variant)
  
  terra::terraOptions(memmax = 6, progress = 0, parallel = FALSE)
  
  outpath <- file.path(outpath_root_input, variant)
  dir.create(outpath, showWarnings = FALSE)
  
  # Read intermediate FL emissions rasters created by 3.0 (reuse instead of regenerate)
  # These rasters were already reclassified and written by the 3.0_fvs_to_raster_wf_emissions.R script
  source_outpath <- file.path(outpath_root_input, "..", basename(outpath_root_input) %>% str_remove("_90p$"), variant)
  
  # Identify which FL levels are present in the 3.0 output directory
  fl_files <- list.files(source_outpath, pattern = "^FL[0-9]+\\.tif$", full.names = TRUE)
  
  if (length(fl_files) == 0) {
    stop("No FL*.tif rasters found in 3.0 output directory: ", source_outpath,
         "\nEnsure 3.0_fvs_to_raster_wf_emissions.R has been run before 3.0.1")
  }
  
  # Extract FL values from filenames and sort them numerically
  fl_values <- as.numeric(str_extract(basename(fl_files), "(?<=FL)\\d+"))
  fl_colnames_present <- paste0("FL", sort(fl_values))
  
  # Load FL emissions rasters in proper order (ascending FL)
  emit_stack <- terra::rast(file.path(source_outpath, paste0(fl_colnames_present, ".tif")))
  
  # Load pre-cropped FL rasters for this variant
  fl.rast <- terra::rast(file.path(fl_clip_dir_input, paste0("fl_clip_", variant, ".tif")))
  
  # Align extents
  emit_stack <- terra::crop(emit_stack, fl.rast)
  
  # Compute probability-weighted mean emissions from the highest 10% of FL probabilities
  # Strategy: For each pixel:
  #   1. Accumulate probabilities starting from highest FL bin and working downward
  #   2. Identify where cumsum reaches/exceeds 0.10
  #   3. Include all FL bins in that top-10% set, with partial weighting at boundary
  #   4. Reweight remaining probabilities to sum to 1
  #   5. Calculate weighted mean emissions using reweighted probabilities
  
  p90.emit <- app(
    c(fl.rast, emit_stack),
    \(x) {
      # First n values are FL probabilities, last n are emissions
      # Bins are ordered: FL1, FL3, FL5, FL7, FL10, FL20 (ascending FL)
      n_fl <- length(x) / 2
      probs <- x[1:n_fl]
      emissions <- x[(n_fl+1):(2*n_fl)]
      
      # Accumulate probabilities from highest FL (last index) downward
      # until we've captured 10% of the probability mass
      cum_prob <- 0
      threshold_idx <- NA_integer_
      partial_prob <- NA_real_
      
      for (i in n_fl:1) {
        # Skip this bin if prob is NA
        if (is.na(probs[i])) next
        
        prob_before <- cum_prob
        cum_prob <- cum_prob + probs[i]
        
        # Check if we've crossed the 0.10 threshold with this bin
        if (!is.na(threshold_idx)) break  # Already found, exit loop
        
        if (cum_prob >= 0.10) {
          threshold_idx <- i
          # Calculate partial contribution for this boundary bin
          remaining_needed <- 0.10 - prob_before
          partial_prob <- min(remaining_needed, probs[i])
        }
      }
      
      # If no bin reaches 0.10, return NA
      if (is.na(threshold_idx)) {
        return(NA_real_)
      }
      
      # Build reweighted probabilities: 
      # - Full probability for all bins > threshold_idx (higher FL values)
      # - Partial probability for boundary bin at threshold_idx
      # - Zero for bins < threshold_idx (lower FL values)
      probs_reweighted <- numeric(n_fl)
      if (threshold_idx < n_fl) {
        probs_reweighted[(threshold_idx+1):n_fl] <- probs[(threshold_idx+1):n_fl]
      }
      probs_reweighted[threshold_idx] <- partial_prob
      
      # Normalize to sum to 1
      prob_sum <- sum(probs_reweighted, na.rm = TRUE)
      if (prob_sum == 0 || is.na(prob_sum)) {
        return(NA_real_)
      }
      probs_reweighted <- probs_reweighted / prob_sum
      
      # Calculate weighted mean emissions
      # Use na.rm = FALSE to propagate NAs; if any input is NA, result should be NA
      weighted_mean <- sum(emissions * probs_reweighted, na.rm = FALSE)
      
      return(weighted_mean)
    }
  )
  
  terra::writeRaster(p90.emit,
                     file.path(outpath, "top10pct_mean_CarbonReleasedFromFire.tif"),
                     overwrite = TRUE)
  
  rm(emit_stack, fl.rast, p90.emit)
  gc()
  message("Variant ", variant, " complete.")
  
}


## ---- Parallel execution over variants ----

future::plan(future.callr::callr, workers = 10)
furrr::future_map(run_variants,
                  ~ process_variant_all_fls_90p(., 
                                              all_dbs, 
                                              tm_clip_dir, 
                                              fl_clip_dir,
                                              fl_colnames,
                                              outpath_root),
                  .progress = TRUE)
future::plan(sequential)

message("Wildfire top-10% emissions rasterization complete.")
