#### 3.0_fvs_to_raster_wf_emissions.R
#### Associates wildfire FVS emissions with pixel locations via TreeMap imputation.
#### For each FVS variant: reclassifies the TMFM2020 raster using per-stand emissions
#### for each flame length bin, then computes conditional expected emissions weighted
#### by FlamStat flame length probability rasters.
#### Outputs: per-variant rasters in data/dp_FVS_postprocess/{wf_run_name}/{VARIANT}/
#### Variant rasters are mosaicked into CONUS layers in 3.2_variant_rasters_merge.R


## ---- Configuration ----

library(here)
source(here("code/FVS_dp/cleaned_workflow/0.0_setup.R"))

# Completed wildfire wet run to rasterize
wf_run_name <- "Wildfire_WetRun_21May26_0855"

# Pre-clipped TreeMap rasters directory (generated by 0.2_tm_clip.R)
tm_clip_dir <- here("data/tm_clip_rasters")

# Pre-clipped FL rasters directory (generated by 0.3_fl_clip.R)
fl_clip_dir <- here("data/fl_clip_rasters")


## ---- Setup ----

all_dbs <- list.files(here("FVS_runs/full", wf_run_name, "outputs"), full.names = TRUE)

outpath_root <- here("data/dp_FVS_postprocess", wf_run_name)
dir.create(outpath_root, showWarnings = FALSE)

# Unique variants present in run outputs
run_variants <- str_sub(basename(all_dbs), -5, -4) %>% unique()


## ---- Per-variant rasterization loop ----

for (variant in run_variants) {

  message("Processing variant: ", variant)

  outpath <- file.path(outpath_root, variant)
  dir.create(outpath, showWarnings = FALSE)

  # Use pre-clipped TreeMap raster for this variant
  tm.clip.path <- file.path(tm_clip_dir, paste0("tm_ref_", variant, ".tif"))

  # Build reclass table from all FL databases for this variant
  variant_dbs <- all_dbs[str_detect(all_dbs, paste0("_", variant, "\\.db$"))]

  reclass.long <- map_dfr(variant_dbs, function(db_path) {
    fl_val <- parse_number(basename(db_path))
    con    <- dbConnect(SQLite(), db_path)
    dat    <- dbGetQuery(con, "SELECT StandID, Carbon_Released_From_Fire
                               FROM FVS_Carbon WHERE Year = 2020")
    dbDisconnect(con)
    
    dat %>% 
      mutate(FL = fl_val,
             StandID = as.integer(StandID))
  })

  fl_levels   <- sort(unique(reclass.long$FL))
  fl_colnames <- paste0("FL", fl_levels)

  reclass.df <- reclass.long %>%
    pivot_wider(names_from   = FL,
                values_from  = Carbon_Released_From_Fire,
                names_prefix = "FL") %>%
    select(StandID, all_of(fl_colnames))

  # Reclassify raster for each FL bin in parallel
  process_var <- function(var) {
    reclass.mat <- reclass.df %>%
      select(from = StandID, to = all_of(var)) %>%
      as.matrix()

    out <- terra::classify(rast(tm.clip.path), reclass.mat, others = NA)
    names(out) <- var

    writeRaster(out, file.path(outpath, paste0(var, ".tif")), overwrite = TRUE)
    gc()
  }

  future::plan(future.callr::callr, workers = parallel::detectCores() - 2)
  furrr::future_map(fl_colnames, process_var)

  # Stack FL emissions rasters (already in ascending FL order)
  emit_stack <- rast(file.path(outpath, paste0(fl_colnames, ".tif")))
  gc()

  # Load pre-cropped FL rasters for this variant
  fl.rast <- rast(file.path(fl_clip_dir, paste0("fl_clip_", variant, ".tif")))
  
  # Align extents by cropping each to the other
  emit_stack <- crop(emit_stack, fl.rast)
  #fl.rast <- crop(fl.rast, emit_stack)

  # Conditional expected emissions (probability-weighted mean across FL bins)
  cond.emit <- app(emit_stack * fl.rast, sum)

  # Conditional standard deviation
  sd.emit <- app(
    fl.rast * (emit_stack - cond.emit)^2,
    \(x) sqrt(sum(x, na.rm = FALSE))
  )

  # Coefficient of variation
  cv.emit <- sd.emit / cond.emit

  writeRaster(cond.emit,
              file.path(outpath, "Conditional_mean_CarbonReleasedFromFire.tif"),
              overwrite = TRUE)
  writeRaster(sd.emit,
              file.path(outpath, "Conditional_sd_CarbonReleasedFromFire.tif"),
              overwrite = TRUE)
  writeRaster(cv.emit,
              file.path(outpath, "Conditional_cv_CarbonReleasedFromFire.tif"),
              overwrite = TRUE)

  rm(reclass.long, reclass.df, emit_stack, fl.rast, cond.emit, sd.emit, cv.emit)
  gc()
  message("Variant ", variant, " complete.")
}
